{$IFNDEF MeService_INC}
{$DEFINE MeService_INC}
{ General Compiler Directives and Compiler Versions Setting }

{------------------------------------------------------------------------------}
{ Please change this to suit your needs                                        }
{------------------------------------------------------------------------------}
{.$DEFINE SUPPORTS_MESERVICE_CALLEX}

{Include Common setting File}
{$I MeSetting.inc}


{***************** These compiler settings shouldn't be changed ***************}

{$ENDIF ~MeService_INC}